### ISSUE TITLE
Missing modules when enabling some ISA extensions

### ISSUE THREAD

**Issue by domenico-rgs** [Fraunhofer-IMS/airisc_core_complex#17]
Hello,
I'm trying to generate the bitstream of the AIRISC core for a Nexys4 DDR board.
The application that I would like to run on this board is an AI one and I was thinking about using some extensions to speed it up.

Now, in the `airi5c_arch_options.vh` file there are some extensions that when defined give errors in synthesis.
Those are: `ISA_EXT_AIACC` that don't find the `airi5c_ai_acc` module and also `ISA_EXT_P` for the SIMD extension saying that module `airi5c_mul_div_simd` is missing 

Would it be possible to fix ?

**Comment by stnolting-ims** [comment]
Hey there,

the AIRISC's AI and SIMD specific extensions are _proprietary_ modules that are _not_ included in the open-source setup (see README's [Additional Modules and Extensions](https://github.com/Fraunhofer-IMS/airisc_core_complex#additional-modules-and-extensions) section). If you would like to add those modules to your setup or if you are thinking about testing them using a pre-build FPGA bitstream please contact [AIRISC-support](mailto:airisc@ims.fraunhofer.de).
